export const GET_REDDIT_POSTS = "GET_REDDIT_POSTS";
export const GET_YELP_DOG_PARKS = "GET_YELP_DOG_PARKS";
export const GET_YELP_DOG_RESTAURANTS = "GET_YELP_DOG_RESTAURANTS";

export const userConstants = {
  LOGIN_REQUEST: "USER_LOGIN_REQUEST",
  LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
  LOGIN_FAILURE: "USER_LOGIN_FAILURE",
  LOGOUT: "USER_LOGOUT",
  SET_USER: "SET_USER",
  REGISTER_REQUEST: "USERS_REGISTER_REQUEST",
  REGISTER_SUCCESS: "USERS_REGISTER_SUCCESS",
  REGISTER_FAILURE: "USERS_REGISTER_FAILURE"
};

export const alertConstants = {
  SUCCESS: "ALERT_SUCCESS",
  ERROR: "ALERT_ERROR",
  CLEAR: "ALERT_CLEAR"
};

export const GET_MEETUPS = "GET_MEETUPS";
export const DELETE_MEETUP = "DELETE_MEETUPS";
export const ADD_MEETUP = "ADD_MEETUP";
export const GET_MEETUP = "GET_MEETUP";
export const UPDATE_MEETUP = "UPDATE_MEETUP";
